---
name: License Exception Request
description: Submit an exception request
title: "[License Exception Request] [Project] [License]"
labels:
  - licensing
assignees: krook,jeefy,joannalee333
body:
  - type: markdown
    attributes:
      value: |
        # Read before proceeding

        Before submitting this License Exception Request, please familiarize yourself with the following:

        - the CNCF IP Policy, from [section 11 of the CNCF Charter](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy), particularly 11(g)
        - the [CNCF Allowlist License Policy](https://github.com/cncf/foundation/blob/main/policies-guidance/allowed-third-party-license-policy.md#cncf-allowlist-license-policy)
        - the [HOWTO for submitting a license exception request](https://contribute.cncf.io/resources/how-to/submit-license-exception-request/)


        If the license for a particular component or dependency is one of the following, please also read the noted guidance before proceeding:


        - AGPL-3.0 (Affero GPL v3): [AGPL guidance](https://github.com/cncf/foundation/blob/main/policies-guidance/agpl-recommendations.md)
        - A component that has relicensed to a non-open source, "source available" license: [Source available guidance](https://github.com/cncf/foundation/blob/main/policies-guidance/source-available-recommendations.md)
        - Interactions generally with source available and other proprietary licenses: [Proprietary / source available guidance](https://github.com/cncf/foundation/blob/main/policies-guidance/proprietary-interactions-guidance.md)


        # When no exception is required

        **Please note**: No exception request is required if the component meets any of the following:


        - is entirely licensed under Apache-2.0 for code; or
        - is entirely licensed under CC-BY-4.0 for documentation; or
        - satisfies the [**CNCF Allowlist License Policy**](https://github.com/cncf/foundation/blob/main/policies-guidance/allowed-third-party-license-policy.md#cncf-allowlist-license-policy)


        # Check for existing exceptions

        Before submitting, please check if an exception already exists for your component(s):

        **[Search the exceptions database](https://exceptions.cncf.io/)**

        If a blanket exception for all CNCF projects already exists for the same package and license, you do not need to request a new one.

        <br />

        ---

        # License Exception Request form

        For any components where none of the above criteria are met, please complete the form below.

  - type: markdown
    attributes:
      value: |
        <br />

        ## :clipboard: Project details

  - type: input
    id: project_name
    attributes:
      label: "For which CNCF project are you requesting exceptions?"
    validations:
      required: true

  - type: dropdown
    id: is_maintainer
    attributes:
      label: "Are you an official maintainer of this project?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />

        ## :package: Component details

        **IMPORTANT**:  You may include multiple packages in this issue only if the answers to **ALL** questions in this form (excluding this Component Details question) are identical for all packages. If any answer differs, please open a **separate issue** for each individual package.

        Please fill in the table below, with one row for each unique component for which a license exception is requested. In the "Project Usage URL" column, please include the URL(s) where the component and its license are located. In the "Purpose" column, please briefly describe (in 1-2 sentences) the functionality of the component and the reason why the Project is using it.

  - type: textarea
    id: component_details
    attributes:
      label: "List of components requiring an exception"
      value: "| Component | Upstream URL | Project Usage URL | License(s) | Purpose |\n|-----------|-----------|-----------|-----------|-----------|\n|            |            |            |            |            |\n|            |            |            |            |            |\n|            |            |            |            |            |"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />

        ## :outbox_tray: Distribution and integration model

  - type: checkboxes
    id: distribution_and_integration_model
    attributes:
      label: "Distribution and integration model"
      description: "Please select all that apply"
      options:
        - label: "**CNCF-Distributed**: The CNCF project will distribute the dependency or the resulting combined artifacts to users."
        - label: "**User-Fetched Dependency**: The CNCF project code will cause the user's system to automatically retrieve the dependency from an upstream source at build, install, or runtime."
        - label: "**System Component**: The CNCF project expects that the dependency will either already be present on the user's system or will be installed independently by the user."
        - label: "**Not Distributed + Not Needed by End User (Internal Project Tooling)**: ALL of the following are true:"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        * The dependency will be used ***only*** in the course of building and testing.
        * The dependency will ***not*** be incorporated in any form into the built artifacts, and it will ***not*** inject any code or libraries into the final artifact. 
        * The CNCF project will ***not*** cause the user's system to retrieve the dependency from an upstream source.
        * Users of the CNCF project will ***not*** need the dependency in order to install or run the CNCF project's code or its distributed artifacts.

  - type: textarea
    id: distribution_and_integration_model_explanation
    attributes:
      label: Please explain
      placeholder: Provide details about your selection(s)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |

        <br />

        ***If the last option ("Not Distributed + Not Needed by End User") is the ONLY option selected for the above question, no license exception is needed and you do not need to answer the remaining questions or submit this form.*** 

        ***If "CNCF-Distributed", "User-Fetched Dependency" or "System Component" applies, please continue to fill out this form.***

  - type: markdown
    attributes:
      value: |
        <br />

        ## :pencil2: Modification status

  - type: checkboxes
    id: modification_status
    attributes:
      label: "Modification status"
      description: "Please select all that apply"
      options:
        - label: "**Modified Upstream**: The CNCF project will patch, alter, or otherwise modify the source code of the dependency and contribute upstream."
        - label: "**Modified Downstream**: The CNCF project will patch, alter, or otherwise modify the source code of the dependency and maintain a downstream fork or local copy."
        - label: "**Unmodified**: The CNCF project will use the dependency exactly as provided by the upstream maintainers without any changes to its source code."
    validations:
      required: true

  - type: textarea
    id: modification_status_explanation
    attributes:
      label: Please explain
      placeholder: Provide details about your selection(s)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />

        ## :building_construction: Structural separation

        Will the upstream code be kept distinct from the CNCF project code?

  - type: checkboxes
    id: structural_separation
    attributes:
      label: "Structural separation"
      description: "Please select all that apply"
      options:
        - label: "**Separated Component**: The dependency's code will either be (a) kept in a distinct directory or module clearly separated from CNCF project code, or (b) retrieved at build/installation time from a third-party repository and never stored in the CNCF project repository."
        - label: '**Intermingled Code**: The dependency''s code will be "mixed in" with CNCF source files, copied into existing project files, or will otherwise lose its distinct directory/module boundary.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ***If "Intermingled Code" is selected, you can skip the remaining questions but still need to submit an exception request using this form.***

  - type: textarea
    id: structural_separation_explanation
    attributes:
      label: Please explain
      placeholder: Provide details about your selection(s)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />

        ## :telephone_receiver: Communication mechanism

  - type: checkboxes
    id: communication_mechanism
    attributes:
      label: "Communication mechanism"
      description: "Please select all that apply"
      options:
        - label: "**Static Linking**: The dependency and the CNCF project code will be combined into a single binary or similar type of artifact during the build process."
        - label: "**Dynamic Linking**: The CNCF project code will interact with the dependency by loading it into the shared address space (memory) at run-time. This includes traditional shared objects compiled into a separate binary, as well as runtime module loading in interpreted or JIT-compiled languages."
        - label: "**Separate Process**: The dependency and the CNCF project code will run as distinct executables and communicate via Inter-Process Communication (e.g., pipes, sockets, or shared files)"
        - label: "**Network Interaction**: The dependency and the CNCF project code will be logically and physically separated by a network boundary, with the CNCF project's code acting as a client or consumer of the remote service and interacting with the dependency exclusively via standardized network protocols."
    validations:
      required: true

  - type: textarea
    id: communication_mechanism_explanation
    attributes:
      label: Please explain
      placeholder: Provide details about your selection(s) or N/A if "intermingled code" was selected for the structural separation question
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />

        ## :arrows_counterclockwise: Data exchange

        Will the interaction involve the exchange of complex, internal data structures?

  - type: checkboxes
    id: data_exchange
    attributes:
      label: "Data exchange"
      description: "Please select all that apply"
      options:
        - label: "**Tightly Coupled**: The upstream dependency and CNCF project code will exchange  complex internal data structures such as shared pointers, class instances, or private memory offsets that require extensive knowledge of the other component's internal memory layout."
        - label: '**Arms-Length Only**: The communication between the dependency and the CNCF project code will be limited to standard serialized data (e.g., JSON, XML, or Protobuf) where data is "flattened" for transport and neither component accesses the other''s internal memory structures.'
    validations:
      required: true

  - type: textarea
    id: data_exchange_explanation
    attributes:
      label: Please explain
      placeholder: Provide details about your selection(s) or N/A if "intermingled code" was selected for the structural separation question
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />

        ## :information_source: Additional information

        Is there any additional information you would like to provide regarding this request?

  - type: textarea
    id: additional_information_explanation
    attributes:
      label: Please explain
      placeholder: Provide details about your selection(s)
