---
name: Licensing Exception Request
description: Submit an exception request
title: "[License Exception Request] [Project] [License]"
labels:
  - licensing
assignees: krook,jeefy,joannalee333
body:
  - type: markdown
    attributes:
      value: >
        ### Please note:
        
        If it is Apache-2.0 for code or CC-BY-4.0 for documentation, no further exception request is required.
        
        
        Does it meet the [Allowlist policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#cncf-allowlist-license-policy)? If so, no further exception request is required.
        
        
        For all other license exception requests, we need the following information.
        
        
        ### License Exception Request:
  - type: textarea
    id: introduction
    attributes:
      label: Component details
      description: What is the third party component (name, URL, and version if available)?
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: License name
      description: What is the full name or title of the license?
    validations:
      required: true
  - type: textarea
    id: modifications
    attributes:
      label: Code modified?
      description: Will the code be used in modified or unmodified form?
    validations:
      required: true
  - type: textarea
    id: license-exception
    attributes:
      label: Changes contributed?
      description: If modified, will changes be contributed back to the upstream project?
  - type: textarea
    id: alternatives
    attributes:
      label: Any alternatives?
      description:
        Are there any alternative components available with equivalent
        functionality under a more permissive license? If so, is it possible to
        use that component instead?
    validations:
      required: true
  - type: textarea
    id: integration
    attributes:
      label: Integrates with other components?
      description:
        How does this component integrate with or interact with, if at all,
        other components of the project?
    validations:
      required: true
